### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by moodfew** [AcidCaos/socialemperors#20]
Ran social empires on arch linux. Firefox with flash player add on and the game is stuck on loading screen

**Comment by moodfew** [comment]
I'm using ruffle

**Comment by 1fxe** [comment]
> I'm using ruffle

Ruffle doesn't support full flash API _**yet**_

**Comment by NeutralTheGreat** [comment]
use flash browser or chomium (linked on github )
