### ISSUE TITLE
Config Requst Url Issue

### ISSUE THREAD

**Issue by nihat-js** [AcidCaos/socialemperors#25]
The game stucks and doesnot start because of that url doesnot respond correctly
http://127.0.0.1:5050/dynamic.flash1.dev.socialpoint.es/appsfb/socialempiresdev/srvempires/get_game_config.php?USERID=8cabdff8-507e-4391-b634-4a60c5df44d9&user_key=123456789&spdebug=1&language=en

**Comment by Nerroth** [comment]
This may be an issue with a corrupted or incompatible save game rather than an issue with sending the config from the server to game client. Backup your saves and remove them then try again. If that doesn't work redownloading everything should fix it.
